module.exports = {
  mode: 'jit',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        hify: {
          50: '#e6fbf0',
          100: '#c5f4d8',
          200: '#88e9b1',
          300: '#48dd87',
          400: '#1ad05c',
          500: '#15b150',
          600: '#10913f',
          700: '#0d6f31',
          800: '#0a4d22',
          900: '#062c14',
        },
      },
      fontFamily: {
        sans: [
          'SF Pro Display',
          'SF Pro Text',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      boxShadow: {
        'glow-sm': '0 0 24px var(--dynamic-bg-light, rgba(250, 35, 59, 0.25))',
        glow: '0 0 36px var(--dynamic-bg-dark, rgba(250, 35, 59, 0.4))',
        'glow-lg': '0 0 60px var(--dynamic-bg-dark, rgba(250, 35, 59, 0.55))',
      },
      animation: {
        'fade-in': 'fadeIn 0.35s ease-out',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.22, 1, 0.36, 1)',
        'pulse-soft': 'pulseSoft 2.4s ease-in-out infinite',
        eq1: 'eq 1.05s ease-in-out infinite',
        eq2: 'eq 0.95s ease-in-out infinite -0.2s',
        eq3: 'eq 0.85s ease-in-out infinite -0.4s',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        slideUp: {
          '0%': { opacity: 0, transform: 'translateY(12px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: 0.7 },
          '50%': { opacity: 1 },
        },
        eq: {
          '0%, 100%': { transform: 'scaleY(0.4)' },
          '50%': { transform: 'scaleY(1)' },
        },
      },
    },
  },
  daisyui: {
    themes: [
      {
        'hify-dark': {
          primary: '#FA233B',
          'primary-focus': '#d21c30',
          'primary-content': '#ffffff',
          secondary: '#A1A1A6',
          'secondary-content': '#0a0a0a',
          accent: '#FA233B',
          'accent-content': '#ffffff',
          neutral: '#1C1C1E',
          'neutral-content': '#F5F5F7',
          'base-100': '#1C1C1E',
          'base-200': '#2C2C2E',
          'base-300': '#000000',
          'base-content': '#F5F5F7',
          info: '#3ABFF8',
          success: '#FA233B',
          warning: '#FBBD23',
          error: '#F87272',
          '--rounded-box': '1.25rem',
          '--rounded-btn': '9999px',
          '--rounded-badge': '9999px',
          '--btn-text-case': 'none',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--border-btn': '1px',
          '--tab-radius': '0.75rem',
        },
      },
      {
        'hify-light': {
          primary: '#FA233B',
          'primary-focus': '#d21c30',
          'primary-content': '#ffffff',
          secondary: '#86868B',
          'secondary-content': '#ffffff',
          accent: '#FA233B',
          'accent-content': '#ffffff',
          neutral: '#F2F2F7',
          'neutral-content': '#1D1D1F',
          'base-100': '#FFFFFF',
          'base-200': '#F2F2F7',
          'base-300': '#FFFFFF',
          'base-content': '#1D1D1F',
          info: '#3ABFF8',
          success: '#FA233B',
          warning: '#FBBD23',
          error: '#F87272',
          '--rounded-box': '1.25rem',
          '--rounded-btn': '9999px',
          '--rounded-badge': '9999px',
          '--btn-text-case': 'none',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--border-btn': '1px',
          '--tab-radius': '0.75rem',
        },
      },
    ],
    darkTheme: 'hify-dark',
  },
  plugins: [require('daisyui')],
}
