services:
  downtify-hisu:
    container_name: downtify-hisu
    image: ghcr.io/hisu87/downtify:latest
    restart: unless-stopped
    ports:
      - '8000:30321'
    volumes:
      - /DATA/Downloads/downtify:/downloads
      - /DATA/AppData/downtify/data:/data
    environment:
      - DOWNTIFY_PORT=30321
    dns:
      - 1.1.1.1
      - 1.0.0.1

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: downtify-hisu
  description:
    en_us: Download your Spotify playlists and songs along with album art and metadata in a self-hosted way.
  tagline:
    en_us: Self-hosted Spotify downloader (Hisu87 fork)
  developer: Hisu87
  author: Hisu87
  icon: https://raw.githubusercontent.com/hisu87/downtify/main/frontend/src/assets/downtify.svg
  thumbnail: ""
  title:
    en_us: Downtify (Hisu87)
  category: Music
  version: 2.8.0
  port_map: "8000"
  index: /
  volumes:
    - type: bind
      target: /downloads
      description:
        en_us: Downloads folder
      source: /DATA/Downloads/downtify
    - type: bind
      target: /data
      description:
        en_us: Data folder
      source: /DATA/AppData/$AppID/data
